<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mayank-PC" failures="2" tests="7" name="Test" time="0.088" errors="0" timestamp="15 Apr 2019 15:48:10 GMT">
  <testcase classname="maventutorial.maven_learning.day1Test" name="carLoan" time="0.001"/>
  <testcase classname="maventutorial.maven_learning.day1Test" name="homeLoan" time="0.0"/>
  <testcase classname="maventutorial.maven_learning.day2Test" name="carLoan" time="0.0"/>
  <testcase classname="maventutorial.maven_learning.day2Test" name="homeLoan" time="0.0"/>
  <testcase classname="maventutorial.maven_learning.day3Test" name="af" time="0.001"/>
  <testcase classname="maventutorial.maven_learning.day3Test" name="test2" time="0.0">
    <failure type="org.testng.TestException" message="
Expected exception of any of types [class java.io.IOException, class java.lang.NullPointerException] but got java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Expected exception of any of types [class java.io.IOException, class java.lang.NullPointerException] but got java.lang.Exception
Caused by: java.lang.Exception
at maventutorial.maven_learning.day3Test.test2(day3Test.java:48)
... 23 more
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="maventutorial.maven_learning.day3Test" name="test3" time="0.0">
    <failure type="org.testng.TestException" message="
Expected exception of type class java.io.IOException but got java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Expected exception of type class java.io.IOException but got java.lang.Exception
Caused by: java.lang.Exception
at maventutorial.maven_learning.day3Test.test3(day3Test.java:54)
... 23 more
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test -->
