<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="5" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-04-15T15:48:09Z" name="Suite" finished-at="2019-04-15T15:48:09Z" duration-ms="88">
    <groups>
      <group name="smoke">
        <method signature="day3Test.af()[pri:0, instance:maventutorial.maven_learning.day3Test@c86b9e3]" name="af" class="maventutorial.maven_learning.day3Test"/>
        <method signature="day3Test.test2()[pri:0, instance:maventutorial.maven_learning.day3Test@c86b9e3]" name="test2" class="maventutorial.maven_learning.day3Test"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2019-04-15T15:48:09Z" name="Test" finished-at="2019-04-15T15:48:09Z" duration-ms="88">
      <class name="maventutorial.maven_learning.day1Test">
        <test-method signature="carLoan()[pri:0, instance:maventutorial.maven_learning.day1Test@10aa41f2]" started-at="2019-04-15T15:48:09Z" name="carLoan" finished-at="2019-04-15T15:48:09Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- carLoan -->
        <test-method signature="homeLoan()[pri:0, instance:maventutorial.maven_learning.day1Test@10aa41f2]" started-at="2019-04-15T15:48:09Z" name="homeLoan" finished-at="2019-04-15T15:48:09Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homeLoan -->
      </class> <!-- maventutorial.maven_learning.day1Test -->
      <class name="maventutorial.maven_learning.day2Test">
        <test-method signature="carLoan()[pri:0, instance:maventutorial.maven_learning.day2Test@3af9c5b7]" started-at="2019-04-15T15:48:09Z" name="carLoan" finished-at="2019-04-15T15:48:09Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- carLoan -->
        <test-method signature="homeLoan()[pri:0, instance:maventutorial.maven_learning.day2Test@3af9c5b7]" started-at="2019-04-15T15:48:09Z" name="homeLoan" finished-at="2019-04-15T15:48:09Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homeLoan -->
      </class> <!-- maventutorial.maven_learning.day2Test -->
      <class name="maventutorial.maven_learning.day3Test">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:maventutorial.maven_learning.day3Test@c86b9e3]" started-at="2019-04-15T15:48:09Z" name="beforeSuite" finished-at="2019-04-15T15:48:09Z" duration-ms="32" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="bfclass()[pri:0, instance:maventutorial.maven_learning.day3Test@c86b9e3]" started-at="2019-04-15T15:48:09Z" name="bfclass" finished-at="2019-04-15T15:48:09Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bfclass -->
        <test-method is-config="true" signature="bf()[pri:0, instance:maventutorial.maven_learning.day3Test@c86b9e3]" started-at="2019-04-15T15:48:09Z" name="bf" finished-at="2019-04-15T15:48:09Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bf -->
        <test-method signature="af()[pri:0, instance:maventutorial.maven_learning.day3Test@c86b9e3]" started-at="2019-04-15T15:48:09Z" name="af" finished-at="2019-04-15T15:48:09Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- af -->
        <test-method is-config="true" signature="bf()[pri:0, instance:maventutorial.maven_learning.day3Test@c86b9e3]" started-at="2019-04-15T15:48:09Z" name="bf" finished-at="2019-04-15T15:48:09Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bf -->
        <test-method signature="test2()[pri:0, instance:maventutorial.maven_learning.day3Test@c86b9e3]" started-at="2019-04-15T15:48:09Z" name="test2" finished-at="2019-04-15T15:48:09Z" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Expected exception of any of types [class java.io.IOException, class java.lang.NullPointerException] but got java.lang.Exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Expected exception of any of types [class java.io.IOException, class java.lang.NullPointerException] but got java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1130)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.Exception
at maventutorial.maven_learning.day3Test.test2(day3Test.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
... 23 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method is-config="true" signature="bf()[pri:0, instance:maventutorial.maven_learning.day3Test@c86b9e3]" started-at="2019-04-15T15:48:09Z" name="bf" finished-at="2019-04-15T15:48:09Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bf -->
        <test-method signature="test3()[pri:0, instance:maventutorial.maven_learning.day3Test@c86b9e3]" started-at="2019-04-15T15:48:09Z" name="test3" finished-at="2019-04-15T15:48:09Z" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Expected exception of type class java.io.IOException but got java.lang.Exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Expected exception of type class java.io.IOException but got java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1130)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.Exception
at maventutorial.maven_learning.day3Test.test3(day3Test.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
... 23 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method is-config="true" signature="afclass()[pri:0, instance:maventutorial.maven_learning.day3Test@c86b9e3]" started-at="2019-04-15T15:48:09Z" name="afclass" finished-at="2019-04-15T15:48:09Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afclass -->
        <test-method is-config="true" signature="hjhj()[pri:0, instance:maventutorial.maven_learning.day3Test@c86b9e3]" started-at="2019-04-15T15:48:09Z" name="hjhj" finished-at="2019-04-15T15:48:09Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hjhj -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:maventutorial.maven_learning.day3Test@c86b9e3]" started-at="2019-04-15T15:48:10Z" name="afterSuite" finished-at="2019-04-15T15:48:10Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- maventutorial.maven_learning.day3Test -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
